# Auto-generated by maxwell-daemon spec — replace step bodies with real code.
from pathlib import Path

import pytest

pytest_bdd = pytest.importorskip("pytest_bdd", reason="optional bdd dependency")
given = pytest_bdd.given
scenarios = pytest_bdd.scenarios
then = pytest_bdd.then
when = pytest_bdd.when

feature_path = Path(__file__).with_name("login.feature")
if feature_path.exists():
    scenarios(str(feature_path))
else:
    pytestmark = pytest.mark.skip(reason="login.feature scaffold not committed")


@given("a user")
def _given_a_user():
    raise NotImplementedError


@when("they log in")
def _when_they_log_in():
    raise NotImplementedError


@then("they see the dashboard")
def _then_they_see_the_dashboard():
    raise NotImplementedError
